// Navbar Items *****************************************/

import HomeIcon from '@mui/icons-material/Home';
import DevicesIcon from '@mui/icons-material/Devices';
import ElectricalIcon from '@mui/icons-material/ElectricalServices';
import BuildIcon from '@mui/icons-material/Build';
import AgricultureIcon from '@mui/icons-material/Agriculture';
import ComputerIcon from '@mui/icons-material/Computer';
import FactoryIcon from '@mui/icons-material/Factory';
import DeckIcon from '@mui/icons-material/Deck';
import MiscellaneousServicesIcon from '@mui/icons-material/MiscellaneousServices';
import { type SvgIconComponent } from '@mui/icons-material';
import type { Product } from '@/interface';

export interface INavbarItem {
   id: string | number;
   name: string;
   label: string;
   icon: SvgIconComponent;
   href: string;
   isSelected?: boolean; // Optional property to indicate if the category is selected
   // If true, the category is active and should be displayed
   isActive?: boolean; // Optional property to indicate if the category is active (default is true)
}

export const categories: INavbarItem[] = [
   {
      id: 'home-appliances',
      name: 'home-appliances',
      label: 'Maishiy texnika',
      isActive: true,
      icon: HomeIcon,
      href: '/category/home-appliances',
   },
   {
      id: 'smart-devices',
      name: 'smart-devices',
      label: 'Aqlli qurilmalar',
      icon: DevicesIcon,
      isActive: true,
      href: '/category/smart-devices',
   },
   {
      id: 'electrical',
      name: 'electrical',
      label: 'Elektr jihozlari',
      isActive: true,
      icon: ElectricalIcon,
      href: '/category/electrical',
   },
   {
      id: 'industrial',
      name: 'industrial',
      label: 'Sanoat texnikalari',
      isActive: true,
      icon: BuildIcon,
      href: '/category/industrial',
   },
   {
      id: 'agriculture',
      name: 'agriculture',
      label: 'Qishloq xo‘jaligi texnikalari',
      icon: AgricultureIcon,
      isActive: true,
      href: '/category/agriculture',
   },
   {
      id: 'computers',
      name: 'computers',
      label: 'Kompyuter va periferiklar',
      icon: ComputerIcon,
      isActive: false,
      href: '/category/computers',
   },
   {
      id: 'factory',
      name: 'factory',
      label: 'Zavod va fabrika texnikalari',
      isActive: true,
      icon: FactoryIcon,
      href: '/category/factory',
   },
   {
      id: 'furniture',
      name: 'furniture',
      label: 'Mebellar',
      isActive: true,
      icon: DeckIcon,
      href: '/category/furniture',
   },
   {
      id: 'metallurgy',
      name: 'metallurgy',
      label: 'Metallurgiya',
      isActive: true,
      icon: MiscellaneousServicesIcon,
      href: '/category/metallurgy',
   },
];

export const exampleData: Product[] = [
   {
      id: 1,
      name: 'Smart TV',
      price: 3500,
      originalPrice: 4000,
      image: '/images/tv.jpg',
      rating: 4.5,
      reviews: 120,
      seller: 'TechStore',
      category: 'home-appliances',
      isHot: true,
      isNew: false,
      description: '55-inch 4K UHD Smart TV with HDR',
      features: ['4K UHD', 'HDR', 'Smart Features', '55-inch'],
      images: ['/images/tv.jpg', '/images/tv2.jpg'],
   },
   {
      id: 2,
      name: 'Laptop',
      price: 5000,
      originalPrice: 6000,
      image: '/images/laptop.jpg',
      rating: 4.2,
      reviews: 80,
      seller: 'TechStore',
      category: 'computers',
      isHot: false,
      isNew: true,
      description: '15-inch laptop with Intel i7 processor',
      features: ['15-inch', 'Intel i7', '8GB RAM', '256GB SSD'],
      images: ['/images/laptop.jpg', '/images/laptop2.jpg'],
   },
   {
      id: 3,
      name: 'Refrigerator',
      price: 2500,
      originalPrice: 3000,
      image: '/images/fridge.jpg',
      rating: 4.3,
      reviews: 90,
      seller: 'TechStore',
      category: 'home-appliances',
      isHot: true,
      isNew: false,
      description: 'Double door refrigerator, 300L',
      features: ['Double door', '300L', 'Smart Features'],
      images: ['/images/fridge.jpg', '/images/fridge2.jpg'],
   },
   {
      id: 4,
      name: 'Washing Machine',
      price: 2000,
      originalPrice: 2500,
      image: '/images/washing-machine.jpg',
      rating: 4.4,
      reviews: 70,
      seller: 'TechStore',
      category: 'home-appliances',
      isHot: false,
      isNew: true,
      description: 'Top-load washing machine, 7kg',
      features: ['Top-load', '7kg', 'Smart Features'],
      images: ['/images/washing-machine.jpg', '/images/washing-machine2.jpg'],
   },
   {
      id: 5,
      name: 'Air Conditioner',
      price: 3000,
      originalPrice: 3500,
      image: '/images/air-conditioner.jpg',
      rating: 4.1,
      reviews: 50,
      seller: 'TechStore',
      category: 'home-appliances',
      isHot: true,
      isNew: false,
      description: 'Split air conditioner, 1.5 ton',
      features: ['Split', '1.5 ton', 'Smart Features'],
      images: ['/images/air-conditioner.jpg', '/images/air-conditioner2.jpg'],
   },
   {
      id: 6,
      name: 'Stove',
      price: 1500,
      originalPrice: 2000,
      image: '/images/stove.jpg',
      rating: 4.6,
      reviews: 60,
      seller: 'TechStore',
      category: 'home-appliances',
      isHot: false,
      isNew: true,
      description: 'Gas stove, 2 burners',
      features: ['Gas', '2 burners', 'Smart Features'],
      images: ['/images/stove.jpg', '/images/stove2.jpg'],
   },
   {
      id: 7,
      name: 'Sofa',
      price: 4000,
      originalPrice: 4500,
      image: '/images/sofa.jpg',
      rating: 4.7,
      reviews: 100,
      seller: 'TechStore',
      category: 'furniture',
      isHot: true,
      isNew: false,
      description: 'Leather sofa, 2 seats',
      features: ['Leather', '2 seats', 'Smart Features'],
      images: ['/images/sofa.jpg', '/images/sofa2.jpg'],
   },
   {
      id: 8,
      name: 'Table',
      price: 800,
      originalPrice: 1000,
      image: '/images/table.jpg',
      rating: 4.8,
      reviews: 40,
      seller: 'TechStore',
      category: 'furniture',
      isHot: false,
      isNew: true,
      description: 'Wooden table, 4 legs',
      features: ['Wooden', '4 legs', 'Smart Features'],
      images: ['/images/table.jpg', '/images/table2.jpg'],
   },
   {
      id: 9,
      name: 'Chair',
      price: 500,
      originalPrice: 600,
      image: '/images/chair.jpg',
      rating: 4.9,
      reviews: 30,
      seller: 'TechStore',
      category: 'furniture',
      isHot: true,
      isNew: false,
      description: 'Leather chair, 2 seats',
      features: ['Leather', '2 seats', 'Smart Features'],
      images: ['/images/chair.jpg', '/images/chair2.jpg'],
   },
   {
      id: 10,
      name: 'Bed',
      price: 2000,
      originalPrice: 2500,
      image: '/images/bed.jpg',
      rating: 4.2,
      reviews: 80,
      seller: 'TechStore',
      category: 'furniture',
      isHot: false,
      isNew: true,
      description: 'Wooden bed, 2 mattresses',
      features: ['Wooden', '2 mattresses', 'Smart Features'],
      images: ['/images/bed.jpg', '/images/bed2.jpg'],
   },
   {
      id: 11,
      name: 'Desk',
      price: 1500,
      originalPrice: 2000,
      image: '/images/desk.jpg',
      rating: 4.3,
      reviews: 50,
      seller: 'TechStore',
      category: 'furniture',
      isHot: true,
      isNew: false,
      description: 'Wooden desk, 4 drawers',
      features: ['Wooden', '4 drawers', 'Smart Features'],
      images: ['/images/desk.jpg', '/images/desk2.jpg'],
   },
];
